// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Identifier = 2,
  Heading = 3,
  Delete = 4,
  Bold = 5,
  UnderLine = 6,
  Italic = 7,
  List = 8,
  Blockquote = 9,
  LineComment = 10,
  Definition = 11,
  Keyword = 12,
  Image = 13
