// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  Identifier = 2,
  Heading = 3,
  Strikethrough = 4,
  Bold = 5,
  Underscore = 6,
  Italic = 7,
  List = 8,
  Blockquote = 9,
  LineComment = 10,
  Definition = 11,
  Keyword = 12,
  Macro = 13,
  Image = 14
